#!/bin/bash

bomgarpresent=$( /bin/ls -d /Users/Shared/bomgar* | /usr/bin/awk -F "Contents" '{ print $1 }' | /usr/bin/cut -d ':' -f1 )
result=$( /usr/bin/defaults read $bomgarpresent/Contents/Info CFBundleGetInfoString | /usr/bin/cut -d ' ' -f1 )
/bin/echo "<result>$result</result>"

exit 0